### ISSUE TITLE
Update for Blender 2.8

### ISSUE THREAD

**Issue by Radivarig** [Radivarig/UvSquares#13]

**Comment by davidsofer** [comment]
Hi,
why you close this issue , is there any solution you publish for Blender 2.80 ??

**Comment by mifth** [comment]
It looks like @Radivarig is working on the 2.8 at diffrent branches. )

Btw, I use UVSquares every time in 2.79. Thanks for the greatest tool.

**Comment by Radivarig** [comment]
Please check this branch [upgrade-7-80](https://github.com/Radivarig/UvSquares/tree/upgrade7-80). It will be merged after a stable Blender 2.80 API release
