### ISSUE TITLE
not work

### ISSUE THREAD

**Issue by DarthMoulByte** [Radivarig/UvSquares#14]
what happen with this ???
can we fix ??

![blender_pUDfgGFobi](https://user-images.githubusercontent.com/24207840/59547830-a6a84000-8f0a-11e9-9900-40a270a69562.png)
![blender_0AoBFsiBSg](https://user-images.githubusercontent.com/24207840/59547832-ac9e2100-8f0a-11e9-9f26-977f3ff9f826.png)
![blender_rbWyN2Sqc6](https://user-images.githubusercontent.com/24207840/59547934-7c578200-8f0c-11e9-9d6c-451aaf4c25d0.png)
![blender_ulxcZP4TI9](https://user-images.githubusercontent.com/24207840/59547947-baed3c80-8f0c-11e9-8bea-c7d81d1aa216.png)

**Comment by Radivarig** [comment]
@DarthMoulByte hi, it seems that this is the correct mapping of 2D texture to 3D faces, if your UVs are straight but the geometry is stretched you will get the above stretched mapping.

I would suggest adding more edges and having the flat parts flat while manually adjusting the rest to the UV texture.
