### ISSUE TITLE
Not working with Blender 2.80 (update to 2.8x required)

### ISSUE THREAD

**Issue by andrelevi** [Radivarig/UvSquares#16]
Getting this issue when attempting to install the add-on using Blender 2.80 2019-07-01.

https://i.imgur.com/AyWJghl.png

**Comment by Radivarig** [comment]
Hi, there are multiple branches, you have to choose the download for 2.80
version

**Comment by andrelevi** [comment]
Thank you for your reply!

When I install 1.8.2 from https://github.com/Radivarig/UvSquares/tree/upgrade7-80_2, I get the "Modules Installed" notification in the bottom right corner, but I don't see UV Squares in the list of add-ons after. But if I install the old 1.5 version I can see UV Squares in the list of add-ons, despite it not working for 2.8. Exactly what this [other person](https://blenderartists.org/t/addon-uvsquares-v1-4-updated-any-shape-supported/613111/108?u=samuraijack22) is seeing.

**Comment by Radivarig** [comment]
@andrelevi what is the full Blender version you have installed?

**Comment by andrelevi** [comment]
@Radivarig Hi, it was the very last when I tried installing UVSquares. Here is my blender version: https://imgur.com/3HFSUKP. Blender 2.80 2019-07-01

**Comment by arvz** [comment]
Hello, I seem to be having the same issue, UV Squares won't show up on the list. I'm already using the latest version (upgrade 7-80_2), and am using Blender 2.8 Release Candidate 2

**Comment by arvz** [comment]
OK I figured it out, turns out I needed to install the .zip file, not the extracted .py file. I looked up tutorials on how to install addons and they said to install the .py file, so that's what I tried.

**Comment by andrelevi** [comment]
@arvz Thanks! That worked for me as well.

**Comment by Shehla-shs** [comment]
Hello getting this issue when attempting to install fast-carve addon. I am using BLENDER v2.83.1 version but when i install the fast-carve add-on zip file it requires to update to 2.8x .what i need to do
