### ISSUE TITLE
To Grid By Shape not working properly

### ISSUE THREAD

**Issue by boski05** [Radivarig/UvSquares#20]
After last update, most of uv islands cannot be ractangle. 
I sending link to file with simple expmple.
Please watch on it.

https://drive.google.com/drive/folders/1fbpwj7wCnLJszVBs8kRMzDkfaPHoxrxv?usp=sharing

**Comment by Radivarig** [comment]
Does this happen for multi island/object only?

**Comment by boski05** [comment]
It's seems to be randomly, sometimes it works when you have only one island selected, but if you mark more it does'nt. In one object or more.

**Comment by Radivarig** [comment]
If the island has no active face selected one is taken from its set. Can
you describe the scenario you have, how do the islands relate to one
another by geometry and what shape is expected from each in the result?

**Comment by boski05** [comment]
I get it, its work when I have active face on specyfic uv island that I want to ractangle, yes?

**Comment by boski05** [comment]
If yes, is there a possibility to ractangle more than one uv island at once?

**Comment by gigazelle** [comment]
I'm also getting this error.

- If the active face is on the UV island I'm working on, alt+E works without issue.
- If the active face is on a different island than the one I have selected, alt+E throws an error and doesn't work.

This can be reproduced by doing the following:

1. Create a Monkey mesh
2. Go to UV > Smart UV project and unwrap it
3. Press A so the entire monkey is selected
4. Go to the UV editor
5. Make sure you have select islands on (not faces/vertices/etc), and select one of the UV islands
6. Press alt+E, and repeat several times for other UV islands
7. After a few times you'll encounter the error
8. Turn on UV sync selection, then select one of the faces on the UV island throwing an error so it's the active face
9. Turn off UV sync selection, then select the entire mesh so you can see the entire UV map again
10. Press alt+E on the UV island that was throwing the error
10. Note that it no longer throws the error.

**Comment by JacRossiter** [comment]
Was this fixed?

**Comment by boski05** [comment]
Yes and no. It works in multiple object selected, but it doesn't when you have more than one uv island selected.

**Comment by gigazelle** [comment]
I've found that if you use the uv face select tool, select a face to be the "root" face, then use the uv island tool to select the rest, it works great. You just have to swap back and forth between the face uv select and island uv select, and can only do 1 island at a time.

**Comment by JacRossiter** [comment]
I played around yesterday and found that being in face select mode works best. Just select the face, then press L to select linked and then straighten. You can also turn this into a little macro using something like pie menu editor which is nice. Now I have something that works quite nicely https://i.gyazo.com/e0102db236eab482b28ff3a89df5e6b7.gif

**Comment by boski05** [comment]
Good idea with this macro. :)

**Comment by Radivarig** [comment]
I've found the issue with automatic selection of active face and fixed in version 1.12.1. 
Please try again without manual selection and let me know.
