### ISSUE TITLE
Addon is non-responsive.

### ISSUE THREAD

**Issue by vakkendwarf** [Radivarig/UvSquares#21]
Pressing any of the functional buttons does not yield any results. The UV is not modified in any way, and I have tried all of them. 
![image](https://user-images.githubusercontent.com/19872682/66409123-65272d80-e9f0-11e9-9ecc-2dcc31280ad5.png)

**Comment by Radivarig** [comment]
Thanks for reporting. What is the blender version (the hash one)? Can you please attach a .blend file with which I can test?

**Comment by vakkendwarf** [comment]
I am using blender 2.80 (don't know what "hash one" means). After a quick restart, in this blend file I have attached there is a different issue (?). Cannot reproduce old one.
![image](https://user-images.githubusercontent.com/19872682/66438180-45adf600-ea2c-11e9-85db-f3b601a083f9.png)

[uv.zip](https://github.com/Radivarig/UvSquares/files/3704793/uv.zip)

**Comment by Radivarig** [comment]
@vakkendwarf Thanks for posting the .blend file! Issue was with auto selection of the active face if none is selected. Fixed in 1.12.1
