### ISSUE TITLE
Getting a ZeroDivisionError when trying to "Grid by Shape" on Andrew's coffee cup tutorial

### ISSUE THREAD

**Issue by kevinisaac** [Radivarig/UvSquares#23]
Python version: 2.8
OS: Arch Linux
Download date: Today

Here's the screenshot:

![DeepinScreenshot_select-area_20191203142411](https://user-images.githubusercontent.com/4241767/70035424-d04c4500-15d8-11ea-88d7-5c07780bfcbf.png)

**Comment by Radivarig** [comment]
Hi what version of the addon are you using?

**Comment by kevinisaac** [comment]
@Radivarig I'm using v1.12.1.

**Comment by Radivarig** [comment]
@kevinisaac can you please post the .blend file?

**Comment by kevinisaac** [comment]
I've made some update since yesterday, but it is the same. Let me know if you have any problems with it.

[donut_new.blend.zip](https://github.com/Radivarig/UvSquares/files/3921428/donut_new.blend.zip)

**Comment by Radivarig** [comment]
There are some double vertices around one of the holes.
You can fix that by selecting the cup in 3d view and hit `F3 > Merge by Distance`.
![2019-12-04-17-41-1575477697](https://user-images.githubusercontent.com/6281737/70162062-5b9f0680-16bd-11ea-8ab7-c433f432bb34.png)
