### ISSUE TITLE
Python script error in function "to grid by shape" (to square grid works fine)

### ISSUE THREAD

**Issue by Rubenzahl** [Radivarig/UvSquares#24]
Hello,

your blender script is great. I am using it in blender 2.81a (newest version)
But I think I found a bug. 
As soon as I select "to grid by shape" - I get a traceback. (see attached picture)
 
![Fehler_Grid](https://user-images.githubusercontent.com/15916136/71647168-dbd37e80-2cf2-11ea-922c-c2d46b818b1a.png)

The function "to square grid" works fine. 

The function "snap to axis" throws the following error:

![Fehler_Snap_to_Axis](https://user-images.githubusercontent.com/15916136/71647207-64eab580-2cf3-11ea-94fe-6ce540d35531.png)

"Snap with equal distance" throws an error too:

![Error_snap_with_equal_distance](https://user-images.githubusercontent.com/15916136/71647227-c448c580-2cf3-11ea-8ca4-6ae903135862.png)

OS: Linux Mint 19.3

Thanks for this plug-in! 

Regards
Peter

**Comment by Radivarig** [comment]
Hi, can you please check if you have duplicated vertices like in this issue #23 ?

**Comment by Rubenzahl** [comment]
You were right. Clicking ALT + M .... B removed the doubles and so the problem disappeared. Sorry for any trouble.

**Comment by Radivarig** [comment]
No problem! I could automate deduplication of the selection, or popup a message that warns about it, since several people have encountered this issue.
