### ISSUE TITLE
keymaps registration error when running `blender -b --python-console`

### ISSUE THREAD

**Issue by nc-mth** [Radivarig/UvSquares#26]
[http://www.dalaifelinto.com/?p=1153](http://www.dalaifelinto.com/?p=1153) reminds us that blender can also be accessed as a python console.

`blender -b --python-console
`

uvsquares causes an exception, and I know why this happens.

```
Exception in module register(): ...\Blender\2.82\scripts\addons\UvSquares-master\__init__.py
Traceback (most recent call last):
  File "...\Blender 2.82\2.82\scripts\modules\addon_utils.py", line 382, in enable
    mod.register()
  File "...\Blender\2.82\scripts\addons\UvSquares-master\uv_squares.py", line 991, in register
    km = wm.keyconfigs.addon.keymaps.new(name='UV Editor', space_type='EMPTY')
AttributeError: 'NoneType' object has no attribute 'keymaps'
Traceback (most recent call last):
  File "...\Blender 2.82\2.82\scripts\modules\addon_utils.py", line 351, in enable
    mod = __import__(module_name)
```

In background mode there's no such thing has keyconfigs.user, because headless mode doesn't need key combos.

Not a serious bug, but worth fixing.

**Comment by Radivarig** [comment]
Fixed in this [commit](https://github.com/Radivarig/UvSquares/commit/c9ac6498683f859945ca3cd2f8fba3c97ff1d05e)
