### ISSUE TITLE
To Grid By Shape in 2.91

### ISSUE THREAD

**Issue by Jamie-txt** [Radivarig/UvSquares#35]
I saw the previous post by boski05 but I haven't been able to find a work around for a similar problem in v2.91.2 with a newly installed copy of UV Squares.

Is there a solution for this or am I doing something wrong?

Here is the behaviour for reference.

Select linked 'L' 
![UV To Grid by Shape Before](https://user-images.githubusercontent.com/78786286/107330507-60e7b480-6afd-11eb-8386-89d2f33119c1.PNG)
Align 'To Grid By Shape'
![UV To Grid by Shape After](https://user-images.githubusercontent.com/78786286/107330563-76f57500-6afd-11eb-9d10-432ffad0efcf.PNG)

**Comment by Radivarig** [comment]
Interesting, can you attach the .blend file?

**Comment by Jamie-txt** [comment]
[https://drive.google.com/file/d/1w7GpQVU7KWBLlxfWjPEktKm8l5mYRzuN/view?usp=sharing](url)

**Comment by Radivarig** [comment]
You have subdivided the seam edges making their faces have more than 4 vertices and non-quads are not supported.

You can select all vertices that are not at the face corners and press `G` twice to slide them along completely to the face corners, then use `F3 > Merge by Distance` to remove doubles, then use the addon again.
