### ISSUE TITLE
Syntax warnings from improperly formatted comparisons

### ISSUE THREAD

**Issue by ThatAsherGuy** [Radivarig/UvSquares#37]
They recently bumped the python version for the Blender dailies, which means that using identity checks on literals — using `is` and `is not` instead of `==` and `!=` when you're doing comparisons with numbers and strings — will now produce syntax warnings.  

It looks like there's only a handful to fix, but I figured it'd be helpful to know in advance, so you don't have to deal with a bunch of duplicate reports when 2.93 ships.

**Comment by Radivarig** [comment]
Thanks!
