### ISSUE TITLE
How can I fix error "Upgrade to 2.8x is required"?

### ISSUE THREAD

**Issue by Achisyg** [Radivarig/UvSquares#39]
I use Blender 2.91 and Blender-Cod 0.5.2. Is there another version I can use or something?

**Comment by Radivarig** [comment]
UvSquares works with 2.8x. How are you trying to install it?

**Comment by Achisyg** [comment]
> 
> 
> UvSquares works with 2.8x. How are you trying to install it?

I just tried to add the .zip file of the addon inside Blender.

**Comment by Radivarig** [comment]
Have you done it from Github with green button `Code  > Download ZIP`?
