### ISSUE TITLE
UV Square not showing in misc tab

### ISSUE THREAD

**Issue by bodhichong** [Radivarig/UvSquares#40]
It seems that the UV Square not showing on the tab when pressing N. Is there a solution?

Version: 2.92.0
![teststs](https://user-images.githubusercontent.com/55965275/111880721-156fd280-89e8-11eb-9313-dfd24aebe507.png)

**Comment by Radivarig** [comment]
You're looking in the `3d View` window, each has its own `N` tab. Click inside the UV Editor window and then press `N`.

**Comment by Radivarig** [comment]
You're looking in the `3d View` window, each has its own N tab. Click inside the `UV Editor` window and then press N.

**Comment by bodhichong** [comment]
Ok, Thank you.
