### ISSUE TITLE
How do I update this add-on?!

### ISSUE THREAD

**Issue by VersionAF** [Radivarig/UvSquares#46]
Hi sry for this dumb question but I don't know how to update this add-on... My current version is V.1.12.1

**Comment by ht-cicd-demo** [comment]
There's a green button that says "Code" at on the top rightish side of the main [github ](https://github.com/Radivarig/UvSquares) page. Make sure your branch is on master (dropdown on left hand side on the same "line" as the code button, it should say "master"). and click the code button triangle thing. It will pop up a box. at the bottom of that box is a line that says "Download Zip". Click that (or [here](https://github.com/Radivarig/UvSquares/archive/refs/heads/master.zip), which is the direct link). It will download a zip called UvSquares_master.zip.

After that you just install it in blender via the install button in preferences/Addons like any other addon and it will update to the new version. The version listed should now be 1.14.1.
