### ISSUE TITLE
"To Grid By Shape" error in update_edit_mesh()

### ISSUE THREAD

**Issue by ThomasRadeke** [Radivarig/UvSquares#47]
Using Blender 3.0.1 and UvSquares 0.14.1 (freshly downloaded from here).

While trying to use "To Grid By Shape", I got an error dialog, pointing to line 480 of uv_squares.py - apparently, "bmesh.update_edit_mesh()" only takes one argument, but two are given.

Removing the second argument restores functionality.

Thanks for this fantastic add-on! :-)

**Comment by YonghuaChan** [comment]
thanks a lot! 😁 It works.
