### ISSUE TITLE
Python errors in Blender 3.1 on Arch Linux

### ISSUE THREAD

**Issue by unfa** [Radivarig/UvSquares#48]
Hi!

I'd love to use UV Squares, but whenever I try I get errors like these:

![image](https://user-images.githubusercontent.com/491704/158351258-6f943cc7-e44d-4800-b5c2-100a00dc94c9.png)

Is there something I could do about this?

**Comment by Radivarig** [comment]
Yes, restart Blender please after you update to version 1.14.1.
