### ISSUE TITLE
Error in the newest version of Blender

### ISSUE THREAD

**Issue by alfvar** [Radivarig/UvSquares#51]
Blender version: 3.1.2
Windows version: Windows-10-10.0.19044-SP0
Python version: 3.10.2

Steps to replicate: Open up a new Blender file, unwrapping the default cube and using any part of the addon on the unwrap
```
uv_squares.py, line 906, in execute
bl_options = {'REGISTER', 'UNDO'}

uv_squares.py, line 49, in main
uv_squares.py, line 57, in main
# context.scene.tool_settings.use_uv_select sync = False
AttributeError: module 'time' has no attribute 'clock'

location: <unknown location>:-1

**Comment by Radivarig** [comment]
What version of UvSquares are you using?
This was fixed here #22
