### ISSUE TITLE
Why does it always make the uv into a straight line

### ISSUE THREAD

**Issue by 9Kronos9** [Radivarig/UvSquares#60]
![8e586b1fb9a193557372b97b3f8e002e](https://github.com/Radivarig/UvSquares/assets/72427646/74efa79f-a654-412f-b77c-ff0ec6c913e9)
![38d389c8d9aa7854a3b7c2ebc2e7256b](https://github.com/Radivarig/UvSquares/assets/72427646/49a0be6a-e24f-4ae3-b759-066559561f85)

**Comment by Radivarig** [comment]
@9Kronos9 it doesn't work on tris, only quads. You can try `Alt + J` first to convert from tris to quads in 3d viewport

**Comment by 9Kronos9** [comment]
Great thank you!

**Comment by jasonswearingen** [comment]
@Radivarig i (a noob) was bit by this...  maybe if you made a small mention of this in a FAQ it would help onboard a lot of beginners
